/**
		JUSTIN REBOK - 2016 - TOTALLY-NOT-ASTROIDS

	PURPOSE OF COMMON.C:
		PROVIDE ALL ESSENTIAL FUNCTIONS THAT ARE NOT RELATED TO DRAWING A SCENE
		I.E. SCORE TRACKING, LIVES, COLLISION CALCULATIONS. 
*/
